/*
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/* 7.1.1.2 Signed Golomb Combination Codes */
uint to_signed(uint x)
{
    return (x >> 1) ^ -(x & 1);
}

/* 7.5.3 Pixel Arrangement */
ivec2 pos_to_block(uint pos, bool chroma)
{
    if (chroma)
        return ivec2(pos >> 1, pos & 1) << 3;
    else
        return ivec2(pos >> 1 & ~1 | (pos & 1), pos >> 1 & 1) << 3;
}

/* 7.1.1.1 Golomb Combination Codes */
uint decode_codeword(inout GetBitContext gb, uint codebook)
{
    uint last_rice_q = (codebook >> 0) & 15,
         krice       = (codebook >> 4) & 15,
         kexp        = (codebook >> 8);

    uint q = 31 - findMSB(show_bits(gb, 32));
    if (q <= last_rice_q) {
        /* Golomb-Rice encoding */
        return (get_bits(gb, krice + q + 1) & ~(1 << krice)) + (q << krice);
    } else {
        /* exp-Golomb encoding */
        return get_bits(gb, (q << 1) + kexp - last_rice_q) - (1 << kexp) + ((last_rice_q + 1) << krice);
    }
}

void decode_comp(in GetBitContext gb, in SliceContext ctx, uint qscale)
{
    uvec3 gid = gl_GlobalInvocationID;
    uint chroma_shift = gid.z != 0 ? log2_chroma_w : 0;

    uint num_blocks  = ctx.mb_count << (2 - chroma_shift);
    ivec2 tex_coords = ivec2(ctx.mb_x << (4 - chroma_shift), ctx.mb_y << 4);

    /* 7.1.1.3 DC Coefficients */
    {
        /* First coeff */
        uint c = to_signed(decode_codeword(gb, 0x650));
        imageStore(dst[gid.z], tex_coords, uvec4((c * qscale) & 0xffff));

        /**
         * Table 9, encoded as (last_rice_q << 0) | (krice or kexp << 4) | ((kexp or kexp + 1) << 8)
         * According to the SMPTE document, abs(prev_dc_diff) should be used
         * to index the table, duplicating the entries removes the abs operation
         */
        const uint dc_codebook[] = { 0x100, 0x210, 0x210, 0x321, 0x321, 0x430, 0x430, };

        uint cw = 5, prev_dc_diff = 0;
        for (int i = 1; i < num_blocks; ++i) {
            cw = decode_codeword(gb, dc_codebook[min(cw, 6)]);

            int s = int(prev_dc_diff) >> 31;
            c += prev_dc_diff = (to_signed(cw) ^ s) - s;

            imageStore(dst[gid.z], tex_coords + pos_to_block(i, gid.z != 0),
                       uvec4((c * qscale) & 0xffff));
        }
    }

    /* 7.1.1.4 AC Coefficients */
    {
        /* Table 10 */
        const uint ac_run_codebook  [] = { 0x102, 0x102, 0x101, 0x101, 0x100, 0x211, 0x211, 0x211,
                                           0x211, 0x210, 0x210, 0x210, 0x210, 0x210, 0x210, 0x320, };

        /* Table 11 */
        const uint ac_level_codebook[] = { 0x202, 0x101, 0x102, 0x100, 0x210, 0x210, 0x210, 0x210, 0x320 };

        /* Figure 4, encoded as (x << 0) | (y << 4) */
        const uint scan_progressive[] = {
            0x00, 0x01, 0x10, 0x11, 0x02, 0x03, 0x12, 0x13,
            0x20, 0x21, 0x30, 0x31, 0x22, 0x23, 0x32, 0x33,
            0x04, 0x05, 0x14, 0x24, 0x15, 0x06, 0x07, 0x16,
            0x25, 0x34, 0x35, 0x26, 0x17, 0x27, 0x36, 0x37,
            0x40, 0x41, 0x50, 0x60, 0x51, 0x42, 0x43, 0x52,
            0x61, 0x70, 0x71, 0x62, 0x53, 0x44, 0x45, 0x54,
            0x63, 0x72, 0x73, 0x64, 0x55, 0x46, 0x47, 0x56,
            0x65, 0x74, 0x75, 0x66, 0x57, 0x67, 0x76, 0x77,
        };

        uint block_mask  = num_blocks - 1;
        uint block_shift = findLSB(num_blocks);

        uint pos = num_blocks - 1, run = 4, level = 1, s;
        while (pos < num_blocks << 6) {
            uint left = left_bits(gb);
            if (left <= 0 || (left < 32 && show_bits(gb, left) == 0))
                break;

            run   = decode_codeword(gb, ac_run_codebook  [min(run,   15)]);
            level = decode_codeword(gb, ac_level_codebook[min(level, 8 )]);
            s     = get_bits(gb, 1);

            pos += run + 1;

            uint bidx  = pos & block_mask, scan = scan_progressive[pos >> block_shift];
            ivec2 spos = pos_to_block(bidx, gid.z != 0);
            ivec2 bpos = ivec2(scan & 0xf, scan >> 4);

            uint c = ((level + 1) ^ -s) + s;
            imageStore(dst[gid.z], tex_coords + spos + bpos,
                       uvec4((c * qscale) & 0xffff));
        }
    }
}

void main(void)
{
    uvec3 gid = gl_GlobalInvocationID;
    if (gid.x >= slice_width || gid.y >= slice_height)
        return;

    uint slice_idx = gid.y * slice_width + gid.x;
    uint slice_off  = slice_offsets[slice_idx],
         slice_size = slice_offsets[slice_idx + 1] - slice_off;

    u8buf bs = u8buf(slice_data + bitstream_start + slice_off);

    /* Decode slice header */
    uint hdr_size = 0, y_size = 0, u_size = 0, v_size = 0, qscale = 0;
    hdr_size = bs[0].v >> 3;

    /* Table 15 */
    uint qidx = clamp(bs[1].v, 1, 224);
    qscale = qidx > 128 ? (qidx - 96) << 2 : qidx;

    y_size = (uint(bs[2].v) << 8) | bs[3].v;
    u_size = (uint(bs[4].v) << 8) | bs[5].v;

    if (alpha_info != 0)
        v_size = (uint(bs[6].v) << 8) | bs[7].v;
    else
        v_size = slice_size - hdr_size - y_size - u_size;

    GetBitContext gb;
    switch (gid.z) {
        case 0:
            init_get_bits(gb, u8buf(bs + hdr_size),                   y_size);
            break;
        case 1:
            init_get_bits(gb, u8buf(bs + hdr_size + y_size),          u_size);
            break;
        case 2:
            init_get_bits(gb, u8buf(bs + hdr_size + y_size + u_size), v_size);
            break;
    }

    /* Entropy decoding, inverse scanning, first part of inverse quantization */
    decode_comp(gb, slice_context[slice_idx], qscale);
}
