/*
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/* Two macroblocks, padded to avoid bank conflicts */
shared float blocks[4*2][8*(8+1)];

uint get_px(uint tex_idx, ivec2 pos) {
#ifndef INTERLACED
    return imageLoad(dst[tex_idx], pos).x;
#else
    return imageLoad(dst[tex_idx], ivec2(pos.x, (pos.y << 1) + bottom_field)).x;
#endif
}

void put_px(uint tex_idx, ivec2 pos, uint v) {
#ifndef INTERLACED
    imageStore(dst[tex_idx], pos, uvec4(v));
#else
    imageStore(dst[tex_idx], ivec2(pos.x, (pos.y << 1) + bottom_field), uvec4(v));
#endif
}

// https://github.com/NVIDIA/cuda-samples/blob/master/Samples/2_Concepts_and_Techniques/dct8x8/dct8x8_kernel2.cuh
#define C_a 1.387039845322148f     //!< a = (2^0.5) * cos(    pi / 16);
#define C_b 1.306562964876377f     //!< b = (2^0.5) * cos(    pi /  8);
#define C_c 1.175875602419359f     //!< c = (2^0.5) * cos(3 * pi / 16);
#define C_d 0.785694958387102f     //!< d = (2^0.5) * cos(5 * pi / 16);
#define C_e 0.541196100146197f     //!< e = (2^0.5) * cos(3 * pi /  8);
#define C_f 0.275899379282943f     //!< f = (2^0.5) * cos(7 * pi / 16);
#define C_norm 0.3535533905932737f //!< 1 / (8^0.5)

/* 7.4 Inverse Transform */
void idct(uint block, uint offset, uint stride) {
    float Vect0 = blocks[block][0*stride + offset];
    float Vect1 = blocks[block][1*stride + offset];
    float Vect2 = blocks[block][2*stride + offset];
    float Vect3 = blocks[block][3*stride + offset];
    float Vect4 = blocks[block][4*stride + offset];
    float Vect5 = blocks[block][5*stride + offset];
    float Vect6 = blocks[block][6*stride + offset];
    float Vect7 = blocks[block][7*stride + offset];

    float Y04P   = Vect0 + Vect4;
    float Y2b6eP = C_b * Vect2 + C_e * Vect6;

    float Y04P2b6ePP   = Y04P + Y2b6eP;
    float Y04P2b6ePM   = Y04P - Y2b6eP;
    float Y7f1aP3c5dPP = C_f * Vect7 + C_a * Vect1 + C_c * Vect3 + C_d * Vect5;
    float Y7a1fM3d5cMP = C_a * Vect7 - C_f * Vect1 + C_d * Vect3 - C_c * Vect5;

    float Y04M   = Vect0 - Vect4;
    float Y2e6bM = C_e * Vect2 - C_b * Vect6;

    float Y04M2e6bMP   = Y04M + Y2e6bM;
    float Y04M2e6bMM   = Y04M - Y2e6bM;
    float Y1c7dM3f5aPM = C_c * Vect1 - C_d * Vect7 - C_f * Vect3 - C_a * Vect5;
    float Y1d7cP3a5fMM = C_d * Vect1 + C_c * Vect7 - C_a * Vect3 + C_f * Vect5;

    blocks[block][0*stride + offset] = C_norm * (Y04P2b6ePP + Y7f1aP3c5dPP);
    blocks[block][7*stride + offset] = C_norm * (Y04P2b6ePP - Y7f1aP3c5dPP);
    blocks[block][4*stride + offset] = C_norm * (Y04P2b6ePM + Y7a1fM3d5cMP);
    blocks[block][3*stride + offset] = C_norm * (Y04P2b6ePM - Y7a1fM3d5cMP);

    blocks[block][1*stride + offset] = C_norm * (Y04M2e6bMP + Y1c7dM3f5aPM);
    blocks[block][5*stride + offset] = C_norm * (Y04M2e6bMM - Y1d7cP3a5fMM);
    blocks[block][2*stride + offset] = C_norm * (Y04M2e6bMM + Y1d7cP3a5fMM);
    blocks[block][6*stride + offset] = C_norm * (Y04M2e6bMP - Y1c7dM3f5aPM);
}

void main(void)
{
    uvec3 gid = gl_GlobalInvocationID, lid = gl_LocalInvocationID;
    uint comp = gid.z, block = (lid.y << 2) | (lid.x >> 3), idx = lid.x & 0x7;
    uint chroma_shift = comp != 0 ? log2_chroma_w : 0;

    if (gid.x > mb_width << (4 - chroma_shift))
        return;

    /* Coalesced load of DCT coeffs in shared memory, second part of inverse quantization */
    [[unroll]]
    for (uint i = 0; i < 8; ++i) {
        int v = sign_extend(int(get_px(comp, ivec2(gid.x, (gid.y << 3) | i))), 16);
        int w = comp == 0 ? qmat_luma[i][idx] : qmat_chroma[i][idx];
        blocks[block][i * 9 + idx] = float(v * w);
    }

    /* Row-wise iDCT */
    barrier();
    idct(block, idx * 9, 1);

    /* Column-wise iDCT */
    barrier();
    idct(block, idx, 9);

    float fact = 1.0f / (1 << (12 - depth)), off = 1 << (depth - 1);
    int maxv = (1 << depth) - 1;

    /* 7.5.1 Color Component Samples. Rescale, clamp and write back to global memory */
    barrier();
    [[unroll]]
    for (uint i = 0; i < 8; ++i) {
        float v = blocks[block][i * 9 + idx] * fact + off;
        put_px(comp, ivec2(gid.x, (gid.y << 3) | i), clamp(int(v), 0, maxv));
    }
}
