/*
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/* Eight macroblocks (maximum slice width) */
shared float blocks[8*4*8*8];

#ifndef INTERLACED
    /* Figure 4, inverted to map scan -> block position */
    const int scan_tbl[] = {
        0x00, 0x01, 0x08, 0x09, 0x02, 0x03, 0x0a, 0x0b,
        0x10, 0x11, 0x18, 0x19, 0x12, 0x13, 0x1a, 0x1b,
        0x04, 0x05, 0x0c, 0x14, 0x0d, 0x06, 0x07, 0x0e,
        0x15, 0x1c, 0x1d, 0x16, 0x0f, 0x17, 0x1e, 0x1f,
        0x20, 0x21, 0x28, 0x30, 0x29, 0x22, 0x23, 0x2a,
        0x31, 0x38, 0x39, 0x32, 0x2b, 0x24, 0x25, 0x2c,
        0x33, 0x3a, 0x3b, 0x34, 0x2d, 0x26, 0x27, 0x2e,
        0x35, 0x3c, 0x3d, 0x36, 0x2f, 0x37, 0x3e, 0x3f,
    };
#else
    /* Figure 5 */
    const int scan_tbl[] = {
        0x00, 0x08, 0x01, 0x09, 0x10, 0x18, 0x11, 0x19,
        0x02, 0x0a, 0x03, 0x0b, 0x12, 0x1a, 0x13, 0x1b,
        0x20, 0x28, 0x21, 0x22, 0x29, 0x30, 0x38, 0x31,
        0x2a, 0x23, 0x2b, 0x32, 0x39, 0x3a, 0x33, 0x3b,
        0x04, 0x0c, 0x05, 0x06, 0x0d, 0x14, 0x1c, 0x15,
        0x0e, 0x07, 0x0f, 0x16, 0x1d, 0x24, 0x2c, 0x25,
        0x1e, 0x17, 0x1f, 0x26, 0x2d, 0x34, 0x3c, 0x35,
        0x2e, 0x27, 0x2f, 0x36, 0x3d, 0x3e, 0x37, 0x3f,
    };
#endif

/* Encoded as ((kexp or kexp + 1) << 8) | (krice or kexp << 4) | (last_rice_q << 0) */
const int first_dc_codebook = 0x650;

/**
 * Table 9
 * According to the SMPTE document, abs(prev_dc_diff) should be used
 * to index the table, duplicating the entries removes the abs operation.
 */
const int dc_codebook      [] = { 0x100, 0x210, 0x210, 0x321,
                                  0x321, 0x430, 0x430, };

/* Table 10 */
const int ac_run_codebook  [] = { 0x102, 0x102, 0x101, 0x101,
                                  0x100, 0x211, 0x211, 0x211,
                                  0x211, 0x210, 0x210, 0x210,
                                  0x210, 0x210, 0x210, 0x320, };

/* Table 11 */
const int ac_level_codebook[] = { 0x202, 0x101, 0x102, 0x100,
                                  0x210, 0x210, 0x210, 0x210,
                                  0x320 };

/* 7.1.1.2 Signed Golomb Combination Codes */
int to_signed(uint x)
{
    return int(x >> 1) ^ -int(x & 1);
}

/* 7.1.1.1 Golomb Combination Codes */
uint decode_codeword(inout GetBitContext gb, int codebook)
{
    int last_rice_q = bitfieldExtract(codebook, 0, 4),
        krice       = bitfieldExtract(codebook, 4, 4),
        kexp        = bitfieldExtract(codebook, 8, 4);

    int q = 31 - findMSB(show_bits(gb, 32));
    if (q <= last_rice_q) {
        /* Golomb-Rice encoding */
        return (get_bits(gb, krice + q + 1) & ~(1 << krice)) + (q << krice);
    } else {
        /* exp-Golomb encoding */
        return get_bits(gb, (q << 1) + kexp - last_rice_q) - (1 << kexp) + ((last_rice_q + 1) << krice);
    }
}

/* 7.1.1 Scanned Coefficients */
void decode_comp(in GetBitContext gb, uvec3 wid, uint num_blocks)
{
    uint block_mask = num_blocks - 1, block_shift = findLSB(num_blocks);

    /* 7.1.1.3 DC Coefficients */
    {
        /* First coeff */
        int c = to_signed(decode_codeword(gb, first_dc_codebook));

        blocks[0] = float(c);

        uint cw = 5;
        int prev_dc_diff = 0;
        for (int i = 1; i < num_blocks; ++i) {
            cw = decode_codeword(gb, dc_codebook[min(cw, 6)]);

            int s = prev_dc_diff >> 31;
            c += prev_dc_diff = (to_signed(cw) ^ s) - s;

            blocks[i << 6] = float(c);
        }
    }

    /* 7.1.1.4 AC Coefficients */
    {
        uint pos = num_blocks - 1, run = 4, level = 1, s;
        while (pos < num_blocks << 6) {
            int left = left_bits(gb);
            if (left <= 0 || (left < 32 && show_bits(gb, left) == 0))
                break;

            run   = decode_codeword(gb, ac_run_codebook  [min(run,   15)]);
            level = decode_codeword(gb, ac_level_codebook[min(level, 8 )]);
            s     = get_bits(gb, 1);

            pos += run + 1;

            int c = int(((level + 1) ^ -s) + s);
            blocks[((pos & block_mask) << 6) + scan_tbl[pos >> block_shift]] = float(c);
        }
    }
}

/* 7.1.2 Scanned Alpha */
void decode_alpha(in GetBitContext gb, uvec3 wid, uint num_blocks)
{
    uint mask = (1 << (4 << alpha_info)) - 1;
    uint num_values = (num_blocks << 3) * min(height - (wid.y << 4), 16);

    int num_cw_bits  = alpha_info == 1 ? 5 : 8,
        num_flc_bits = alpha_info == 1 ? 9 : 17;

    uint alpha_rescale_lshift = alpha_info == 1 ? depth - 8 : 16,
         alpha_rescale_rshift = 16 - depth;

    uint alpha = -1;
    for (uint pos = 0; pos < num_values;) {
        uint diff, run;

        /* Decode run value */
        {
            uint bits = show_bits(gb, num_cw_bits), q = num_cw_bits - 1 - findMSB(bits);

            /* Tables 13/14 */
            if (q != 0) {
                uint m = (bits >> 1) + 1, s = bits & 1;
                diff = (m ^ -s) + s;
                skip_bits(gb, num_cw_bits);
            } else {
                diff = get_bits(gb, num_flc_bits);
            }

            alpha = alpha + diff & mask;
        }

        /* Decode run length */
        {
            uint bits = show_bits(gb, 5), q = 4 - findMSB(bits);

            /* Table 12 */
            if (q == 0) {
                run = 1;
                skip_bits(gb, 1);
            } else if (q <= 4) {
                run = bits + 1;
                skip_bits(gb, 5);
            } else {
                run = get_bits(gb, 16) + 1;
            }

            run = min(run, num_values - pos);
        }

        /**
         * FFmpeg doesn't support color and alpha with different depth,
         * so we need to rescale to the color range.
         */
        uint val = (alpha << alpha_rescale_lshift) | (alpha >> alpha_rescale_rshift);
        for (uint end = pos + run; pos < end; ++pos)
            blocks[pos] = float(val & 0xffff);
    }
}

/* 7.4 Inverse Transform */
void idct(uint offset, uint stride) {
    /* Adapted from faanidct.c */
#define B0 1.0000000000000000000000f
#define B1 1.3870398453221474618216f // cos(pi*1/16)sqrt(2)
#define B2 1.3065629648763765278566f // cos(pi*2/16)sqrt(2)
#define B3 1.1758756024193587169745f // cos(pi*3/16)sqrt(2)
#define B4 1.0000000000000000000000f // cos(pi*4/16)sqrt(2)
#define B5 0.7856949583871021812779f // cos(pi*5/16)sqrt(2)
#define B6 0.5411961001461969843997f // cos(pi*6/16)sqrt(2)
#define B7 0.2758993792829430123360f // cos(pi*7/16)sqrt(2)

#define A4 0.7071067811865475244008f // cos(pi*4/16)
#define A2 0.9238795325112867561281f // cos(pi*2/16)

    float s17 = blocks[1*stride + offset] + blocks[7*stride + offset];
    float d17 = blocks[1*stride + offset] - blocks[7*stride + offset];
    float s53 = blocks[5*stride + offset] + blocks[3*stride + offset];
    float d53 = blocks[5*stride + offset] - blocks[3*stride + offset];

    float od07 =  s17 + s53;
    float od25 = (s17 - s53) * (2*A4);

    float od34 = d17 * (2*(B6-A2)) - d53 * (2*A2);
    float od16 = d53 * (2*(A2-B2)) + d17 * (2*A2);

    od16 -= od07;
    od25 -= od16;
    od34 += od25;

    float s26 = blocks[2*stride + offset] + blocks[6*stride + offset];
    float d26 = blocks[2*stride + offset] - blocks[6*stride + offset];
    d26 *= 2*A4;
    d26 -= s26;

    float s04 = blocks[0*stride + offset] + blocks[4*stride + offset];
    float d04 = blocks[0*stride + offset] - blocks[4*stride + offset];

    float os07 = s04 + s26;
    float os34 = s04 - s26;
    float os16 = d04 + d26;
    float os25 = d04 - d26;

    blocks[0*stride + offset] = os07 + od07;
    blocks[7*stride + offset] = os07 - od07;
    blocks[1*stride + offset] = os16 + od16;
    blocks[6*stride + offset] = os16 - od16;
    blocks[2*stride + offset] = os25 + od25;
    blocks[5*stride + offset] = os25 - od25;
    blocks[3*stride + offset] = os34 - od34;
    blocks[4*stride + offset] = os34 + od34;
}

void main(void)
{
    uvec3 wid = gl_WorkGroupID, lid = gl_LocalInvocationID, wgs = gl_WorkGroupSize;
    if (wid.x >= slice_width || wid.y >= slice_height)
        return;

    uint slice_idx = wid.y * slice_width + wid.x;
    uint slice_off  = slice_offsets[slice_idx],
         slice_size = slice_offsets[slice_idx + 1] - slice_off;

    u8buf bs = u8buf(slice_data + slice_off);

    /* Decode slice header */
    uint hdr_size, y_size, u_size, v_size, a_size;
    hdr_size = bs[0].v >> 3;

    /* Table 15 */
    uint qidx   = clamp(bs[1].v, 1, 224),
         qscale = qidx > 128 ? (qidx - 96) << 2 : qidx;

    y_size = (uint(bs[2].v) << 8) | bs[3].v;
    u_size = (uint(bs[4].v) << 8) | bs[5].v;

    /**
     * The alpha_info field can be 0 even when an alpha plane is present,
     * if skip_alpha is enabled, so use the header size instead.
     */
    if (hdr_size > 6)
        v_size = (uint(bs[6].v) << 8) | bs[7].v;
    else
        v_size = slice_size - hdr_size - y_size - u_size;

    a_size = slice_size - hdr_size - y_size - u_size - v_size;

    GetBitContext gb;
    switch (wid.z) {
        case 0:
            init_get_bits(gb, u8buf(bs + hdr_size),                            int(y_size));
            break;
        case 1:
            init_get_bits(gb, u8buf(bs + hdr_size + y_size),                   int(u_size));
            break;
        case 2:
            init_get_bits(gb, u8buf(bs + hdr_size + y_size + u_size),          int(v_size));
            break;
        case 3:
            init_get_bits(gb, u8buf(bs + hdr_size + y_size + u_size + v_size), int(a_size));
            break;
    }

    /**
     * Support for the grayscale "extension" in the prores_aw encoder.
     * According to the spec, entropy coded data should never be empty,
     * and instead contain at least the DC coefficients.
     * This avoids undefined behavior.
     */
    if (left_bits(gb) == 0)
        return;

    /* Clear shared memory */
    for (uint i = lid.x; i < blocks.length() * 4; i += wgs.x)
        blocks[i] = 0.0f;
    barrier();

    /**
     * 4 ProRes Frame Structure
     * ProRes tiles pictures into a grid of slices, whose size is determined
     * by the log2_slice_width parameter (height is always 1 MB).
     * Each slice has a width of (1 << log2_slice_width) MBs, until the picture
     * cannot accommodate a full one. At this point, the remaining space
     * is recursively completed using the first smaller power of two that fits
     * (see Figure 1).
     * The maximum number of extra slices is 3, when log2_slice_width is 3,
     * with sizes 4, 2 and 1 MBs.
     * The mb_width parameter therefore also represents the number of full slices,
     * when interpreted as a fixed-point number with log2_slice_width fractional bits.
     */
    uint frac      = bitfieldExtract(uint(mb_width), 0, log2_slice_width),
         num_extra = bitCount(frac);

    uint diff = slice_width - wid.x - 1,
         off  = max(int(diff - num_extra + 1) << 2, 0);

    uint log2_width = min(findLSB(frac - diff >> diff) + diff + off, log2_slice_width);
    uint mb_count   = 1 << log2_width;

    bool luma = wid.z == 0, alpha = wid.z == 3;
    uint chroma_shift = (luma || alpha) ? 0 : log2_chroma_w;
    uint num_blocks   = mb_count << (2 - chroma_shift);

    if (lid.x == 0) {
        if (!alpha) /* Color entropy decoding, block-level inverse scanning */
            decode_comp(gb, wid, num_blocks);
        else        /* Alpha entropy decoding */
            decode_alpha(gb, wid, num_blocks);
    }
    barrier();

    /* Inverse quantization */
    uint qmat_off = luma ? 0 : 64;
    for (uint i = lid.x; !alpha && i < (num_blocks<<6); i += wgs.x)
        blocks[i] *= scaled_qmat[qmat_off + (i & 63)] * qscale;
    barrier();

    /* Inverse transform, horizontal */
    for (uint i = lid.x; !alpha && i < (num_blocks<<3); i += wgs.x)
        idct(i << 3, 1);
    barrier();

    /* Inverse transform, vertical */
    for (uint i = lid.x; !alpha && i < (num_blocks<<3); i += wgs.x)
        idct(((i & ~7) << 3) + (i & 7), 8);
    barrier();

    /* Rescale */
    float scale_fact = 1.0f / (1 << (12 - depth)), scale_off = 1 << (depth - 1);
    for (uint i = lid.x; !alpha && i < (num_blocks<<6); i += wgs.x)
        blocks[i] = blocks[i] * scale_fact + scale_off;
    barrier();

    uint mb_x = (min(wid.x, slice_width - num_extra) << log2_slice_width) +
                (frac & (0xf << log2_width + 1)),
         mb_y = wid.y;
    ivec2 base_pos = ivec2(mb_x << (4 - chroma_shift), mb_y << 4);

    /**
     * Output row-wise for write coalescing.
     * This also handles slice-level inverse scanning for color components,
     * and clamping to the allowed output range.
     */
    int maxv = (1 << depth) - 1;
    uint shift_x1 = alpha ? 0 : (4 - uint(luma)), shift_x2 = alpha ? 0 : 4;
    uint shift_y1 = alpha ? (4 + log2_width) : 3, shift_y2 = alpha ? (4 + log2_width) : (3 + uint(luma));
    for (uint y = 0; y < 16; ++y) {
        uint y_off = ((y & ~7) << shift_y2) + ((y & 7) << shift_y1);
        for (uint x = lid.x; x < (num_blocks<<2); x += wgs.x) {
            uint smem_pos = ((x & ~0xf) << shift_x2) + ((x & 8) << shift_x1) + (x & 7) + y_off;
            int v = clamp(int(blocks[smem_pos]), 0, maxv);

            ivec2 surf_pos = base_pos + ivec2(x, y);
#ifdef INTERLACED
            surf_pos.y = (surf_pos.y << 1) + bottom_field;
#endif

            imageStore(dst[wid.z], surf_pos, uvec4(v));
        }
    }
}
